/**
 * Injects a one-line coordination notice directly into a file that's under
 * active same-branch conflict — the only channel guaranteed to reach an
 * agent that has never heard of spidersan: the next time it reads or
 * re-reads the file it's editing, the notice is just... there.
 *
 * Idempotent: replaces its own previous marker line in place rather than
 * stacking duplicates on every re-conflict.
 */

import { readFileSync, writeFileSync, renameSync, existsSync, statSync, chmodSync } from 'fs';
import { extname } from 'path';
import { randomBytes } from 'crypto';

const MARKER = 'spidersan-coord:';

// ponytail: hardcoded extension→comment-syntax map, not a real language
// detector — add an entry if a language you care about isn't covered.
const LINE_COMMENT: Record<string, string> = {
    '.ts': '//', '.tsx': '//', '.js': '//', '.jsx': '//', '.mjs': '//', '.cjs': '//',
    '.go': '//', '.rs': '//', '.java': '//', '.c': '//', '.cpp': '//', '.h': '//', '.swift': '//',
    '.py': '#', '.rb': '#', '.sh': '#', '.yml': '#', '.yaml': '#', '.toml': '#',
};
const BLOCK_COMMENT: Record<string, [string, string]> = {
    '.md': ['<!--', '-->'],
    '.html': ['<!--', '-->'],
    '.css': ['/*', '*/'],
};

function formatMarkerLine(ext: string, text: string): string {
    if (BLOCK_COMMENT[ext]) {
        const [open, close] = BLOCK_COMMENT[ext];
        return `${open} ${MARKER} ${text} ${close}`;
    }
    const prefix = LINE_COMMENT[ext] ?? '#';
    return `${prefix} ${MARKER} ${text}`;
}

export function secondsAgo(isoTimestamp: string): number {
    return Math.max(0, Math.round((Date.now() - new Date(isoTimestamp).getTime()) / 1000));
}

// A shebang MUST be the literal first line, or the OS refuses to execute the
// file (found live during a foolproof review: prepending above `#!/usr/bin/env
// bash` turned a working script into `permission denied`). Insert after it.
function insertionIndex(lines: string[]): number {
    return lines[0]?.startsWith('#!') ? 1 : 0;
}

// "(Ns ago)" is a lie the moment nothing re-triggers it — a foolproof review
// found it reads "0s ago" forever once the conflict stops recurring, so a
// reader can never tell fresh from ancient. Print the wall-clock time instead;
// it's honestly a snapshot, not a claim about "right now".
function formatAsOf(isoTimestamp: string): string {
    return new Date(isoTimestamp).toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
}

function atomicWrite(filePath: string, content: string): void {
    // A file actively appended to by another process (e.g. a watch daemon's
    // own stdout redirect sitting in the watched directory) can interleave
    // with a direct writeFileSync and corrupt — seen live as garbled padding
    // during dogfooding. Write to a sibling temp path and rename into place;
    // the appender's fd just becomes stale rather than the file getting torn.
    const tmpPath = `${filePath}.spidersan-coord-${randomBytes(4).toString('hex')}.tmp`;
    // Rename swaps in a fresh inode at the default umask — an executable
    // script would silently lose its +x bit (found live: a shebang script
    // still had the right content but `permission denied` on run). Carry
    // the original mode over before the swap.
    const originalMode = existsSync(filePath) ? statSync(filePath).mode : undefined;
    writeFileSync(tmpPath, content);
    if (originalMode !== undefined) chmodSync(tmpPath, originalMode);
    renameSync(tmpPath, filePath);
}

function readTextFile(filePath: string): string | null {
    if (!existsSync(filePath)) return null;
    let content: string;
    try {
        content = readFileSync(filePath, 'utf-8');
    } catch {
        return null; // binary or unreadable — don't touch it
    }
    if (content.includes('\0')) return null; // binary guard
    return content;
}

/**
 * Insert (or replace, if already present) a one-line coordination notice
 * into `filePath` — after a shebang if there is one, otherwise at the top.
 * Returns true if the file was written, false if the file doesn't exist, is
 * binary-looking, or the notice was unchanged.
 */
export function injectCoordComment(filePath: string, claimantAgent: string, claimedAtIso: string): boolean {
    const content = readTextFile(filePath);
    if (content === null) return false;

    const ext = extname(filePath);
    const text = `also being edited by ${claimantAgent} as of ${formatAsOf(claimedAtIso)} — expect overwrites, re-check before saving. (auto-generated by spidersan watch; removed automatically once resolved, safe to ignore)`;
    const markerLine = formatMarkerLine(ext, text);

    const lines = content.split('\n');
    const existingIdx = lines.findIndex(l => l.includes(MARKER));

    let newLines: string[];
    if (existingIdx !== -1) {
        if (lines[existingIdx] === markerLine) return false; // already up to date
        newLines = [...lines];
        newLines[existingIdx] = markerLine;
    } else {
        const at = insertionIndex(lines);
        newLines = [...lines.slice(0, at), markerLine, ...lines.slice(at)];
    }

    atomicWrite(filePath, newLines.join('\n'));
    return true;
}

/**
 * Strip a previously-injected coordination marker once its conflict is no
 * longer active — otherwise it squats at the top of the file forever after
 * a single collision, indistinguishable from a live warning. Returns true
 * if the file was changed.
 */
export function removeCoordComment(filePath: string): boolean {
    const content = readTextFile(filePath);
    if (content === null) return false;

    const lines = content.split('\n');
    const idx = lines.findIndex(l => l.includes(MARKER));
    if (idx === -1) return false;

    const newLines = [...lines.slice(0, idx), ...lines.slice(idx + 1)];
    atomicWrite(filePath, newLines.join('\n'));
    return true;
}
