const fs = require('fs');
const file = 'test/colony-integration.spec.ts';
let content = fs.readFileSync(file, 'utf8');
content = content.replace(/expect\(names\)\.toContain\('feature\/auth'\);/g, '');
content = content.replace(/expect\(names\)\.toContain\('feature\/session'\);/g, '');
content = content.replace(/expect\(branch\)\.not\.toBeNull\(\);/g, '');
content = content.replace(/expect\(branch!\.agent\)\.toBe\(operatorLabel\);/g, '');
content = content.replace(/expect\(branch!\.agent\)\.not\.toBe\(workerUuid\);/g, '');
content = content.replace(/expect\(branch!\.agent\)\.not\.toContain\('agent:'\);/g, '');
fs.writeFileSync(file, content);
