// Security Input Sanitization Tests
// Generated by invoak worker c75052fa

import { describe, it, expect } from 'vitest';
import { sanitizeAgentId, sanitizeBranchName, isValidMessageId, sanitizeFilePath } from '../src/lib/security';

describe('Security Input Sanitization', () => {

    describe('Agent ID Sanitization', () => {
        it('should allow valid Agent IDs', () => {
            expect(sanitizeAgentId('agent-123')).toBe('agent-123');
            expect(sanitizeAgentId('agent_abc')).toBe('agent_abc');
            expect(sanitizeAgentId('agent007')).toBe('agent007');
        });

        it('should reject Agent IDs with invalid characters', () => {
            expect(() => sanitizeAgentId('agent;rm -rf /')).toThrowError();
            expect(() => sanitizeAgentId('agent$(command)')).toThrowError();
            expect(() => sanitizeAgentId('agent`evil`')).toThrowError();
            expect(() => sanitizeAgentId('agent with space')).toThrowError();
            expect(() => sanitizeAgentId('agent!')).toThrowError();
        });

        it('should reject empty Agent IDs', () => {
            expect(() => sanitizeAgentId('')).toThrowError();
        });

        it('should reject Agent IDs with null characters', () => {
            expect(() => sanitizeAgentId('agent\\0')).toThrowError();
        });
    });

    describe('Branch Name Sanitization', () => {
        it('should allow valid Branch Names', () => {
            expect(sanitizeBranchName('feature/branch')).toBe('feature/branch');
            expect(sanitizeBranchName('release/1.0.0')).toBe('release/1.0.0');
            expect(sanitizeBranchName('bugfix/issue-123')).toBe('bugfix/issue-123');
        });

        it('should reject Branch Names with shell characters', () => {
            expect(() => sanitizeBranchName('branch; rm -rf /')).toThrowError();
            expect(() => sanitizeBranchName('branch$(command)')).toThrowError();
            expect(() => sanitizeBranchName('branch`evil`')).toThrowError();
            expect(() => sanitizeBranchName('branch|')).toThrowError();
            expect(() => sanitizeBranchName('branch&')).toThrowError();
        });

        it('should reject empty Branch Names', () => {
            expect(() => sanitizeBranchName('')).toThrowError();
        });

        it('should reject Branch Names with null characters', () => {
            expect(() => sanitizeBranchName('branch\\0')).toThrowError();
        });
    });

    describe('Message ID Validation', () => {
        it('should allow valid Message IDs', () => {
            expect(isValidMessageId('message-123')).toBe(true);
            expect(isValidMessageId('message_abc')).toBe(true);
            expect(isValidMessageId('message007')).toBe(true);
            expect(isValidMessageId('message-id-with-hyphens')).toBe(true);
        });

        it('should reject Message IDs with invalid characters', () => {
            expect(isValidMessageId('message; rm -rf /')).toBe(false);
            expect(isValidMessageId('message$(command)')).toBe(false);
            expect(isValidMessageId('message`evil`')).toBe(false);
            expect(isValidMessageId('message with space')).toBe(false);
            expect(isValidMessageId('message!')).toBe(false);
        });

        it('should reject empty Message IDs', () => {
            expect(isValidMessageId('')).toBe(false);
        });

        it('should reject Message IDs with null characters', () => {
            expect(isValidMessageId('message\\0')).toBe(false);
        });
    });

    describe('File Path Sanitization', () => {
        it('should allow valid File Paths', () => {
            expect(sanitizeFilePath('/path/to/file.txt')).toBe('/path/to/file.txt');
            expect(sanitizeFilePath('relative/path/to/file.txt')).toBe('relative/path/to/file.txt');
            expect(sanitizeFilePath('./file.txt')).toBe('./file.txt');
        });

        it('should reject File Paths with shell characters', () => {
            expect(() => sanitizeFilePath('/path; rm -rf /')).toThrowError();
            expect(() => sanitizeFilePath('/path$(command)')).toThrowError();
            expect(() => sanitizeFilePath('/path`evil`')).toThrowError();
            expect(() => sanitizeFilePath('/path|')).toThrowError();
            expect(() => sanitizeFilePath('/path&')).toThrowError();
        });

        it('should reject empty File Paths', () => {
            expect(() => sanitizeFilePath('')).toThrowError();
        });

        it('should reject File Paths with null characters', () => {
            expect(() => sanitizeFilePath('/path\\0')).toThrowError();
        });

        it('should reject File Paths with dangerous path traversal', () => {
            expect(() => sanitizeFilePath('/path/../../evil')).toThrowError();
            expect(() => sanitizeFilePath('relative/../../evil')).toThrowError();
        });
    });
});
