name: ts-review

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**/*.ts'
      - '!**/*.d.ts'
      - '!**/node_modules/**'

jobs:
  ts-review:
    uses: treebird7/treebird/.github/workflows/ts-review.yml@main
    with:
      repo-name: treebird7/spidersan-oss
    secrets:
      TREEBIRD_TOKEN: ${{ secrets.TREEBIRD_TOKEN }}
